=== deegree/deegree3/deegree-core/deegree-core-coverage/src/main/resources/META-INF/schemas/datasource/coverage/raster/3.4.0/raster.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns:raster="http://www.deegree.org/datasource/coverage/raster" xmlns="http://www.w3.org/2001/XMLSchema"
  targetNamespace="http://www.deegree.org/datasource/coverage/raster" elementFormDefault="qualified"
  xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" jaxb:version="2.1">
  <annotation>
    <appinfo>
      <jaxb:schemaBindings>
        <jaxb:package name="org.deegree.coverage.raster.io.jaxb" />
      </jaxb:schemaBindings>
    </appinfo>
  </annotation>

  <element name="Raster">
    <annotation>
      <appinfo>
        <jaxb:class name="RasterConfig" />
      </appinfo>
    </annotation>
    <complexType>
      <complexContent>
        <extension base="raster:AbstractRasterType">
          <attribute name="configVersion" use="required">
            <simpleType>
              <restriction base="string">
                <enumeration value="3.4.0" />
                <enumeration value="3.0.0" />
              </restriction>
            </simpleType>
          </attribute>
        </extension>
      </complexContent>
    </complexType>
  </element>

  <element name="MultiResolutionRaster">
    <annotation>
      <documentation>A multi resolution raster wraps (single) rasters and adds a resolution of each raster.
      </documentation>
      <appinfo>
        <jaxb:class name="MultiResolutionRasterConfig" />
      </appinfo>
    </annotation>
    <complexType>
      <sequence>
        <element name="StorageCRS" minOccurs="0" type="string" />
        <element name="Resolution" maxOccurs="unbounded">
          <complexType>
            <complexContent>
              <extension base="raster:AbstractRasterType">
                <attribute name="res" type="double" />
              </extension>
            </complexContent>
          </complexType>
        </element>
      </sequence>
      <attribute name="originLocation" default="center" type="raster:OriginLocation" />
      <attribute name="readWorldFiles" default="true" type="boolean" />
      <attribute name="nodata" type="decimal" />
      <attribute name="configVersion" use="required">
        <simpleType>
          <restriction base="string">
            <enumeration value="3.4.0" />
            <enumeration value="3.0.0" />
          </restriction>
        </simpleType>
      </attribute>
    </complexType>
  </element>

  <complexType name="AbstractRasterType" abstract="true">
    <sequence>
      <element name="StorageCRS" minOccurs="0" type="string" />
      <choice minOccurs="0">
        <element name="RasterFile">
          <complexType>
            <simpleContent>
              <extension base="string">
                <attribute name="imageIndex" type="int" use="optional" />
              </extension>
            </simpleContent>
          </complexType>
        </element>
        <element name="RasterDirectory">
          <complexType>
            <simpleContent>
              <extension base="string">
                <attribute name="recursive" type="boolean" default="false" />
              </extension>
            </simpleContent>
          </complexType>
        </element>
      </choice>
    </sequence>
    <attribute name="readWorldFiles" default="true" type="boolean" />
    <attribute name="originLocation" default="center" type="raster:OriginLocation" />
    <attribute name="nodata" type="decimal" />
  </complexType>

  <simpleType name="OriginLocation">
    <restriction base="string">
      <enumeration value="center" />
      <enumeration value="outer" />
    </restriction>
  </simpleType>

</schema>

=== deegree/deegree3/deegree-core/deegree-core-coverage/src/main/resources/META-INF/schemas/datasource/coverage/raster/directory.xml
<?xml version="1.0" encoding="UTF-8"?>
<MultiResolutionRaster xmlns="http://www.deegree.org/datasource/coverage/raster"
  originLocation="outer" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.deegree.org/datasource/coverage/raster https://schemas.deegree.org/core/3.5/datasource/coverage/raster/raster.xsd">
  <StorageCRS>EPSG:26912</StorageCRS>
  <Resolution res="2" nodata="0">
    <!--
      This datasource configuration shows, how defining a RasterDirectory as datasource for deegree WMS works. You have
      to look up for the crs in the root element and for the fileType attribute in the RasterDirectory element similar
      to the configuration of a single RasterFile.
    -->
    <RasterDirectory>../../data/utah/raster/Satellite_Provo/1</RasterDirectory>
  </Resolution>
  <Resolution res="4" nodata="0">
    <RasterDirectory>../../data/utah/raster/Satellite_Provo/2</RasterDirectory>
  </Resolution>
  <Resolution res="8" nodata="0">
    <RasterDirectory>../../data/utah/raster/Satellite_Provo/3</RasterDirectory>
  </Resolution>
  <Resolution res="16" nodata="0">
    <RasterDirectory>../../data/utah/raster/Satellite_Provo/4</RasterDirectory>
  </Resolution>
</MultiResolutionRaster>
