=== deegree/deegree3/deegree-services/deegree-services-wms/src/main/resources/META-INF/schemas/services/wms/3.2.0/wms_configuration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns:wms="http://www.deegree.org/services/wms" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2001/XMLSchema"
  targetNamespace="http://www.deegree.org/services/wms" elementFormDefault="qualified" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb"
  jaxb:version="2.1">

  <annotation>
    <appinfo>
      <jaxb:schemaBindings>
        <jaxb:package name="org.deegree.services.jaxb.wms" />
      </jaxb:schemaBindings>
    </appinfo>
  </annotation>

  <element name="ScaleDenominators" type="wms:ScaleDenominatorsType" />
  <complexType name="ScaleDenominatorsType">
    <attribute name="min" type="double" use="required" />
    <attribute name="max" type="double" use="required" />
    <attribute name="native" type="double" use="optional" />
  </complexType>
  <element name="BoundingBox" type="wms:BoundingBoxType" />
  <complexType name="BoundingBoxType">
    <sequence>
      <element name="LowerCorner" type="wms:PositionType" />
      <element name="UpperCorner" type="wms:PositionType" />
    </sequence>
    <attribute name="crs" type="anyURI" use="optional" />
    <attribute name="dimensions" type="int" use="optional" />
  </complexType>
  <simpleType name="PositionType">
    <list itemType="double" />
  </simpleType>

  <element name="deegreeWMS">
    <complexType>
      <sequence>
        <element name="SupportedVersions" minOccurs="0">
          <complexType>
            <sequence>
              <element name="Version" type="wms:WMSVersionType" maxOccurs="unbounded" />
            </sequence>
          </complexType>
        </element>
        <!-- if set, it will be checked upon startup if metadata ids for layers actually exist -->
        <element name="MetadataStoreId" type="string" minOccurs="0" />
        <!-- if set, this template will be used for generating MetadataURL elements for layers (default is to use an internal 
          CSW if available) -->
        <element name="MetadataURLTemplate" minOccurs="0" type="string" />
        <element name="ServiceConfiguration" type="wms:ServiceConfigurationType" />
        <element name="FeatureInfoFormats" minOccurs="0" type="wms:FeatureInfoFormatsType" />
        <element name="ExtendedCapabilities" minOccurs="0" maxOccurs="unbounded">
          <complexType>
            <sequence>
              <any processContents="lax">
                <annotation>
                  <appinfo>
                    <jaxb:dom />
                  </appinfo>
                </annotation>
              </any>
            </sequence>
          </complexType>
        </element>
        <element name="LayerLimit" minOccurs="0" type="positiveInteger"/>
        <element name="MaxWidth" minOccurs="0" type="positiveInteger"/>
        <element name="MaxHeight" minOccurs="0" type="positiveInteger"/>
      </sequence>
      <attribute name="configVersion" use="required" type="wms:ConfigVersionType" />
    </complexType>
  </element>

  <complexType name="ServiceConfigurationType">
    <sequence>
      <element name="DefaultLayerOptions" type="wms:LayerOptionsType" minOccurs="0" />
      <choice>
        <element name="ThemeId" type="string" minOccurs="0" maxOccurs="unbounded" />
        <element ref="wms:AbstractLayer" minOccurs="0" />
      </choice>
    </sequence>
  </complexType>

  <complexType name="FeatureInfoFormatsType">
    <sequence>
      <element name="GetFeatureInfoFormat" minOccurs="0" maxOccurs="unbounded">
        <complexType>
          <sequence>
            <choice>
              <element name="File" type="string" />
              <element name="XSLTFile">
                <complexType>
                  <simpleContent>
                    <extension base="string">
                      <attribute name="gmlVersion" type="wms:GMLVersionType" default="GML_32" use="optional" />
                    </extension>
                  </simpleContent>
                </complexType>
              </element>
            </choice>
            <element name="Format" type="string" />
          </sequence>
        </complexType>
      </element>
    </sequence>
  </complexType>

  <complexType name="LayerOptionsType">
    <sequence>
      <element name="AntiAliasing" type="string" minOccurs="0" />
      <element name="RenderingQuality" type="string" minOccurs="0" />
      <element name="Interpolation" type="string" minOccurs="0" />
      <element name="MaxFeatures" type="int" minOccurs="0" />
      <element name="FeatureInfoRadius" type="int" minOccurs="0" />
    </sequence>
  </complexType>

  <complexType name="BaseAbstractLayerType" />

  <element name="AbstractLayer" type="wms:BaseAbstractLayerType" abstract="true" />

  <complexType name="DirectStyleType">
    <sequence>
      <element name="File" type="string" />
      <element name="Name" type="string" minOccurs="0" />
      <choice minOccurs="0">
        <element name="LegendConfigurationFile" type="string" />
        <element name="LegendGraphicFile">
          <complexType>
            <simpleContent>
              <extension base="string">
                <attribute name="outputGetLegendGraphicUrl" type="boolean" default="true" use="optional" />
              </extension>
            </simpleContent>
          </complexType>
        </element>
      </choice>
    </sequence>
  </complexType>

  <complexType name="SLDStyleType">
    <sequence>
      <element name="File" type="string" />
      <element name="NamedLayer" type="string" />
      <sequence minOccurs="0" maxOccurs="unbounded">
        <element name="Name" type="string" minOccurs="0" />
        <element name="UserStyle" type="string" />
        <choice minOccurs="0">
          <element name="LegendConfigurationFile" type="string" />
          <element name="LegendGraphicFile">
            <complexType>
              <simpleContent>
                <extension base="string">
                  <attribute name="outputGetLegendGraphicUrl" type="boolean" default="true" use="optional" />
                </extension>
              </simpleContent>
            </complexType>
          </element>
        </choice>
      </sequence>
    </sequence>
  </complexType>

  <complexType name="DimensionType">
    <sequence>
      <element name="Name" type="string" minOccurs="0" />
      <element name="Property" type="QName" />
      <element name="DefaultValue" type="string" minOccurs="0" />
      <element name="MultipleValues" type="boolean" default="0" minOccurs="0" />
      <element name="NearestValue" type="boolean" default="0" minOccurs="0" />
      <element name="Current" type="boolean" default="0" minOccurs="0" />
      <element name="Units" type="string" minOccurs="0" />
      <element name="UnitSymbol" type="string" minOccurs="0" />
      <element name="Extent" type="string" />
    </sequence>
    <attribute name="isTime" type="boolean" use="optional" default="false" />
    <attribute name="isElevation" type="boolean" use="optional" default="false" />
  </complexType>

  <complexType name="AbstractLayerType">
    <complexContent>
      <extension base="wms:BaseAbstractLayerType">
        <sequence>
          <element name="Name" type="string" minOccurs="0" />
          <element name="Title" type="string" minOccurs="0" />
          <element name="Abstract" type="string" minOccurs="0" />
          <element name="MetadataSetId" type="string" minOccurs="0" />
          <element ref="wms:Keywords" minOccurs="0" maxOccurs="unbounded" />
          <element ref="wms:BoundingBox" minOccurs="0" />
          <element name="CRS" type="string" minOccurs="0" />
          <element name="Dimension" type="wms:DimensionType" minOccurs="0" maxOccurs="unbounded" />
          <choice>
            <element ref="wms:ScaleDenominators" minOccurs="0" />
            <element name="ScaleUntil" type="double" minOccurs="0" />
            <element name="ScaleAbove" type="double" minOccurs="0" />
          </choice>
          <element ref="wms:AbstractLayer" minOccurs="0" maxOccurs="unbounded" />
          <choice minOccurs="0">
            <element name="FeatureStoreId" type="string" />
            <element name="CoverageStoreId" type="string" />
            <element name="RemoteWMSStoreId" type="string" />
          </choice>
          <element name="DirectStyle" type="wms:DirectStyleType" minOccurs="0" maxOccurs="unbounded" />
          <element name="SLDStyle" type="wms:SLDStyleType" minOccurs="0" maxOccurs="unbounded" />
          <element name="LayerOptions" type="wms:LayerOptionsType" minOccurs="0" />
        </sequence>
        <attribute name="queryable" type="boolean" use="optional" />
      </extension>
    </complexContent>
  </complexType>

  <element name="RequestableLayer" substitutionGroup="wms:AbstractLayer">
    <complexType>
      <complexContent>
        <restriction base="wms:AbstractLayerType">
          <sequence>
            <element name="Name" type="string" />
            <element name="Title" type="string" />
            <element name="Abstract" type="string" minOccurs="0" />
            <element name="MetadataSetId" type="string" minOccurs="0" />
            <element ref="wms:Keywords" minOccurs="0" maxOccurs="unbounded" />
            <element ref="wms:BoundingBox" minOccurs="0" />
            <element name="CRS" type="string" minOccurs="0" />
            <element name="Dimension" type="wms:DimensionType" minOccurs="0" maxOccurs="unbounded" />
            <choice>
              <element ref="wms:ScaleDenominators" minOccurs="0" />
              <element name="ScaleUntil" type="double" minOccurs="0" />
              <element name="ScaleAbove" type="double" minOccurs="0" />
            </choice>
            <element ref="wms:AbstractLayer" minOccurs="0" maxOccurs="unbounded" />
            <choice minOccurs="0">
              <element name="FeatureStoreId" type="string" />
              <element name="CoverageStoreId" type="string" />
              <element name="RemoteWMSStoreId" type="string" />
            </choice>
            <element name="DirectStyle" type="wms:DirectStyleType" minOccurs="0" maxOccurs="unbounded" />
            <element name="SLDStyle" type="wms:SLDStyleType" minOccurs="0" maxOccurs="unbounded" />
            <element name="LayerOptions" type="wms:LayerOptionsType" minOccurs="0" />
          </sequence>
          <attribute name="queryable" type="boolean" use="optional" />
        </restriction>
      </complexContent>
    </complexType>
  </element>

  <element name="UnrequestableLayer" substitutionGroup="wms:AbstractLayer">
    <complexType>
      <complexContent>
        <restriction base="wms:AbstractLayerType">
          <sequence>
            <element name="Title" type="string" />
            <element name="Abstract" type="string" minOccurs="0" />
            <element ref="wms:Keywords" minOccurs="0" maxOccurs="unbounded" />
            <element ref="wms:BoundingBox" minOccurs="0" />
            <element name="CRS" type="string" minOccurs="0" />
            <choice>
              <element ref="wms:ScaleDenominators" minOccurs="0" />
              <element name="ScaleUntil" type="double" minOccurs="0" />
              <element name="ScaleAbove" type="double" minOccurs="0" />
            </choice>
            <element ref="wms:AbstractLayer" minOccurs="0" maxOccurs="unbounded" />
            <choice minOccurs="0">
              <element name="FeatureStoreId" type="string" />
              <element name="CoverageStoreId" type="string" />
              <element name="RemoteWMSStoreId" type="string" />
            </choice>
            <element name="DirectStyle" type="wms:DirectStyleType" minOccurs="0" maxOccurs="unbounded" />
            <element name="SLDStyle" type="wms:SLDStyleType" minOccurs="0" maxOccurs="unbounded" />
            <element name="LayerOptions" type="wms:LayerOptionsType" minOccurs="0" />
          </sequence>
          <attribute name="queryable" type="boolean" use="optional" />
        </restriction>
      </complexContent>
    </complexType>
  </element>

  <element name="LogicalLayer" substitutionGroup="wms:AbstractLayer">
    <complexType>
      <complexContent>
        <restriction base="wms:AbstractLayerType">
          <sequence>
            <element ref="wms:BoundingBox" minOccurs="0" />
            <choice>
              <element ref="wms:ScaleDenominators" minOccurs="0" />
              <element name="ScaleUntil" type="double" minOccurs="0" />
              <element name="ScaleAbove" type="double" minOccurs="0" />
            </choice>
            <element ref="wms:AbstractLayer" minOccurs="0" maxOccurs="unbounded" />
            <choice minOccurs="0">
              <element name="FeatureStoreId" type="string" />
              <element name="CoverageStoreId" type="string" />
              <element name="RemoteWMSStoreId" type="string" />
            </choice>
            <element name="DirectStyle" type="wms:DirectStyleType" minOccurs="0" maxOccurs="unbounded" />
            <element name="SLDStyle" type="wms:SLDStyleType" minOccurs="0" maxOccurs="unbounded" />
            <element name="LayerOptions" type="wms:LayerOptionsType" minOccurs="0" />
          </sequence>
          <attribute name="queryable" type="boolean" use="optional" />
        </restriction>
      </complexContent>
    </complexType>
  </element>

  <element name="DynamicLayer" substitutionGroup="wms:AbstractLayer">
    <complexType>
      <complexContent>
        <extension base="wms:BaseAbstractLayerType">
          <choice>
            <element name="ShapefileDirectory" type="string" />
            <element name="PostGIS">
              <complexType>
                <simpleContent>
                  <extension base="string">
                    <attribute name="schema" use="optional" type="string" />
                  </extension>
                </simpleContent>
              </complexType>
            </element>
          </choice>
        </extension>
      </complexContent>
    </complexType>
  </element>

  <element name="StatisticsLayer" substitutionGroup="wms:AbstractLayer">
    <complexType>
      <complexContent>
        <extension base="wms:BaseAbstractLayerType" />
      </complexContent>
    </complexType>
  </element>

  <simpleType name="WMSVersionType">
    <restriction base="string">
      <enumeration value="1.1.1" />
      <enumeration value="1.3.0" />
      <!-- enumeration value="2.0.0" / -->
    </restriction>
  </simpleType>

  <!-- ========================================================== -->
  <element name="Keywords" type="wms:KeywordsType" />
  <!-- ========================================================== -->
  <complexType name="KeywordsType">
    <annotation>
      <documentation>
        Unordered list of one or more commonly used or formalised word(s) or
        phrase(s) used to describe
        the
        subject. When needed, the optional "type" can name the type of the
        associated list of keywords that shall
        all
        have
        the same type. Also when needed, the codeSpace attribute of that
        "type" can reference the type name
        authority
        and/or thesaurus. If the xml:lang attribute is not included in a
        Keyword element, then no language is
        specified
        for that element unless specified by another means. All Keyword
        elements in the same Keywords element
        that share
        the same xml:lang attribute value represent different
        keywords in that language.
      </documentation>
      <documentation>
        For OWS use, the optional thesaurusName element was omitted as being
        complex information that
        could
        be referenced by the codeSpace attribute of the Type element.
      </documentation>
    </annotation>
    <sequence>
      <element name="Keyword" type="wms:LanguageStringType" maxOccurs="unbounded" />
      <element name="Type" type="wms:CodeType" minOccurs="0" />
    </sequence>
  </complexType>
  <complexType name="LanguageStringType">
    <annotation>
      <documentation>
        Text string with the language of the string identified as recommended in
        the XML 1.0 W3C
        Recommendation, section 2.12.
      </documentation>
    </annotation>
    <simpleContent>
      <extension base="string">
        <attribute name="lang" type="string" use="optional" />
      </extension>
    </simpleContent>
  </complexType>
  <complexType name="CodeType">
    <annotation>
      <documentation>
        Name or code with an (optional) authority. If the codeSpace attribute is
        present, its value shall
        reference a dictionary, thesaurus, or authority for the name or code, such as
        the organisation who assigned the
        value, or the dictionary from which it is taken.
      </documentation>
      <documentation>
        Type copied from basicTypes.xsd of GML 3 with documentation edited, for
        possible use outside the
        ServiceIdentification section of a service metadata document.
      </documentation>
    </annotation>
    <simpleContent>
      <extension base="string">
        <attribute name="codeSpace" type="anyURI" use="optional" />
      </extension>
    </simpleContent>
  </complexType>

  <simpleType name="ConfigVersionType">
    <restriction base="string">
      <enumeration value="3.0.0" />
      <enumeration value="3.1.0" />
      <enumeration value="3.2.0" />
    </restriction>
  </simpleType>

  <simpleType name="GMLVersionType">
    <restriction base="string">
      <enumeration value="GML_2" />
      <enumeration value="GML_30" />
      <enumeration value="GML_31" />
      <enumeration value="GML_32" />
    </restriction>
  </simpleType>

</schema>

=== deegree/deegree3/deegree-demos/deegree-geosciml-demo/src/main/webapp/WEB-INF/conf/services/wms.xml
<?xml version="1.0" ?>
<deegreeWMS xmlns="http://www.deegree.org/services/wms" configVersion="0.5.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.deegree.org/services/wms http://schemas.deegree.org/wms/0.5.0/wms_configuration.xsd">
  <ServiceConfiguration>

    <UnrequestableLayer>
      <Title>GeoSciML Demo WMS</Title>
      <CRS>EPSG:4283 EPSG:4326</CRS>
      
      <RequestableLayer>
        <Name>MappedFeature</Name>
        <Title>Mapped Features</Title>
        <FeatureStoreId>geosciml</FeatureStoreId>
        <DirectStyle>
          <File>../styles/MappedFeature.se</File>
        </DirectStyle>
      </RequestableLayer>
      <RequestableLayer>
        <Name>MappedFeatureLabel</Name>
        <Title>Mapped Features, Labels</Title>
        <ScaleDenominators max="30000" min="0"/>
        <FeatureStoreId>geosciml</FeatureStoreId>
        <DirectStyle>
          <File>../styles/MappedFeatureLabel.se</File>
        </DirectStyle>
      </RequestableLayer>
    </UnrequestableLayer>
  </ServiceConfiguration>
</deegreeWMS>
